### ISSUE TITLE
tooltip 的z-index在有些情况下不准的问题

### ISSUE THREAD

**Issue by ZhiJieZhang1** [chiawiansup/vue-element-table-tooltip#1]
情况：
比如在一个页面有两个弹窗，一个dialog，一个drawer，在dialog里使用了vue-element-table-tooltip。

复现过程：
先打开drawer，再关闭。再打开dialog，table，hover时，vue-element-table-tooltip的tooltip第一次触发是看不见的，只有下一次hover时才会出现。
先对drawer打开->关闭，打开->关闭 n次，那么dialog里tooltip的hover只有在n次之后才会正常显示。

结论：
原因猜测是z-index 值获取有问题。

**Comment by chiawiansup** [comment]
f196a5c

**Comment by jiayuansen** [comment]
0179b18

**Comment by ZhiJieZhang1** [comment]
> [0179b18](https://github.com/chiawiansup/vue-element-table-tooltip/commit/0179b180e9ae08b90ff9faf397d894cb9fde0fab)

hi，首先感谢你这么快速的响应并改动。但是，似乎问题并没有得到解决。我看了源码和实现原理，发现是element-ui 的不同引用导致的。你似乎得改造下你的项目中package.json和npm publish，发布的npm包中不要包含不必要的node-modules，比如vue和element-ui。其次，demo部分要跟这个包主要功能区分开，当然demo要不要发到包里，普遍认为最好不要，因为是不必要的且可以从github源码里找到demo。不然就是徒增npm包的大小。

**Comment by jiayuansen** [comment]
> hi，首先感谢你这么快速的响应并改动。但是，似乎问题并没有得到解决。我看了源码和实现原理，发现是element-ui 的不同引用导致的。你似乎得改造下你的项目中package.json和npm publish，发布的npm包中不要包含不必要的node-modules，比如vue和element-ui。其次，demo部分要跟这个包主要功能区分开，当然demo要不要发到包里，普遍认为最好不要，因为是不必要的且可以从github源码里找到demo。不然就是徒增npm包的大小。

hi，感谢你对这个小项目的关注。我按照复现过程另外写了一个类似的demo，并在实际项目中验证这个问题，但并没有复现出上文所提到的bug，可能是缺少某些边界条件，不知是否方便提供下复现的代码？
> 第一次触发是看不见的，只有下一次hover时才会出现

这个可能与popover实例没有及时销毁有关，因此在上一次提交中，代码逻辑改为一个表格实例对应一个popover实例，用WeakMap保存这个关系，并在表格实例的生命周期里面处理这个关系，但实际的问题可能并不在此处。
